config/routes.rb
Rails.application.routes.draw do

  resources :applications do
    member do
      patch :approve, to: 'applications#approve'
      get :deny, to: 'applications#deny'
      get :card, to: 'cards#show'
    end
    resources :application_supplements, only: [:update, :show] do
      member do
        get :approve, to: 'application_supplements#approve'
        get :deny, to: 'application_supplements#deny'
      end
    end
  end

  devise_for :users

  root 'applications#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  before_create :set_token
  before_create :set_haiku
  before_create :geocode
  before_create :set_initial_status
  before_save :set_coords

  has_one :card, dependent: :destroy
  belongs_to :user

  has_many :application_supplements, dependent: :destroy

  monetize :fee_cents, allow_nil: true
  geocoded_by :full_street_address
  has_paper_trail only: [:status]

  enum status: [:submitted, :processing, :approved, :denied, :canceled, :deferred, :insufficient, :waiting_for_documents] do

    event :approve do
      before do
        self.approved_at = Time.zone.now
      end
      transition [:submitted, :processing, :deferred, :insufficient, :waiting_for_documents] => :approved
    end

    event :deny do
      before do
        self.approved_at = nil
      end
      transition [:approved, :processing] => :denied
    end

    event :defer do
      transition [:submitted, :processing] => :deferred
    end

    event :mark_insufficient do
      transition [:submitted, :processing] => :insufficient
    end

    event :begin_processing do
      transition all - [:denied] => :processing
    end

    event :request_documents do
      transition :submitted => :waiting_for_documents
    end
  end

  def full_street_address
    if address2.blank?
      "#{address1}, #{city}, #{state}, #{zip}"
    else
      "#{address1}, #{address2}, #{city}, #{state}, #{zip}"
    end
  end

  def regenerate_token
    self.token = ULID.generate
    self.save
  end

  def regenerate_haiku
    self.haiku = Haikunator.haikunate(1000, '-')
    self.save
  end

  def show_title
    self.title.blank? ? "Membership Application (#{token})" : title
  end

  private

  def set_token
    self.token = ULID.generate
  end

  def set_haiku
    self.haiku = Haikunator.haikunate(1000, '-')
  end

  def set_coords
    if self.address1_changed?
      self.geocode
    end
  end

  def set_initial_status
    self.status = 0
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_supplement.rb
class ApplicationSupplement < ApplicationRecord
  belongs_to :application
  before_create :set_token
  after_update :check_if_all_uploaded

  mount_uploader :document, DocumentUploader
  has_paper_trail only: [:status]

  enum status: [:waiting, :pending_review, :approved, :denied] do
    event :send_for_review do
      transition :waiting => :pending_review
    end

    event :approve do
      transition :pending_review => :approved
    end

    event :deny do
      transition [:pending_review, :waiting] => :denied
    end
  end

  private

  def set_token
    self.token = ULID.generate
  end

  def check_if_all_uploaded
    if self.application.application_supplements.where(status: 0).any?
      return false
    else
      if self.application.status == 'waiting_for_documents'
        self.application.begin_processing
        NotificationMailer.documents_received(self.application).deliver_now
        NotificationMailer.admin_doc_email(self.application).deliver_now
      end
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  before_create :set_card_number
  before_create :set_expiration
  belongs_to :application

  private

  def set_card_number
    self.card_number = ULID.generate
  end

  def set_expiration
    self.expiration = Time.zone.now + 1.year
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :applications

  before_create :set_token
  before_create :set_haiku

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private

  def set_token
    self.token = ULID.generate
  end

  def set_haiku
    self.haiku = Haikunator.haikunate(1000, '-')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/application_supplements_controller.rb
class ApplicationSupplementsController < ApplicationController
  def show
    @supplement = ApplicationSupplement.find params[:id]
    if @supplement.document.blank?
      redirect_to @supplement.application
    else
      redirect_to @supplement.document.url
    end
  end

  def update
    @supplement = ApplicationSupplement.find params[:id]

    if @supplement.update(supplement_params)
      @supplement.send_for_review
      redirect_to application_url(@supplement.application_id)
    else
      redirect_to Application.find params[:application_id]
    end
  end

  def approve
    @supplement = ApplicationSupplement.find params[:id]
    if @supplement.approve
      flash.notice = "#{@supplement.title} approved."
    else
      flash.notice = "Error."
    end
    redirect_to @supplement.application
  end

  def deny
    @supplement = ApplicationSupplement.find params[:id]
    if @supplement.deny
      flash.notice = "#{@supplement.title} denied."
      NotificationMailer.document_denied(@supplement).deliver_now
      @supplement.application.deny
      NotificationMailer.application_denied(@supplement.application).deliver_now
      @supplement.application.card.destroy if @supplement.application.card
    else
      flash.notice = "Error."
    end
    redirect_to @supplement.application
  end

  private

  def supplement_params
    params.require(:application_supplement).permit(:document)
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :find_app, only: [:show, :edit, :update]

  def index
    @apps = current_user.applications
  end

  def show
  end

  def new
    @app = Application.new
  end

  def create
    @app = current_user.applications.new(app_params)
    if @app.save
      ['Driver License', 'Bank Statement or Utility Bill', 'Recent Photograph'].each do |doc|
        AddSupplement.run(application: @app, title: doc)
      end
      @app.request_documents
      redirect_to application_url(@app)
    else
      render :new
    end
  end

  def edit
  end

  def approve
    @app = Application.find(params[:id])

    if @app.approve
      @card = @app.build_card
      @card.save
      NotificationMailer.application_approved(@app).deliver_now
    end

    redirect_to @app
  end

  def deny
    @app = Application.find(params[:id])
    if @app.deny
      NotificationMailer.application_denied(@app).deliver_now
      @app.card.destroy if @app.card
    end
    redirect_to @app
  end

  private

  def app_params
    params.require(:application).permit(:first_name, :last_name, :email, :address1, :city, :state, :zip, :fee_cents, :title)
  end

  def find_app
    @app = Application.find params[:id]
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @app = Application.find params[:id]

    redirect_to @app if @app and @app.card.blank?

    respond_to do |format|
      format.pdf do
        pdf = IdCardPdf.new(@app)
        send_data pdf.render, filename: @app.card.card_number + '.pdf', type: 'application/pdf', disposition: 'inline'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/application_supplements_helper.rb
module ApplicationSupplementsHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/applications/_app_card.html.slim
.card.app-status

  .card-block
    h3.card-title
      | Application Status
    .card-text
      p.lead Your application with Haiku <span class="tag tag-pill tag-success">#{@app.haiku}</span> is <strong>#{@app.status.split('_').join(' ').upcase}</strong>.
      table.table.table-bordered.table-striped
        tr
          th TITLE
          td== @app.show_title
        - @app.attributes.slice('status').each do |k, v|
          tr
            th== k.upcase
            td== v
        tr
          th Location
          td
            == image_tag "http://maps.googleapis.com/maps/api/staticmap?center=&zoom=15&scale=false&size=300x150&maptype=roadmap&key=AIzaSyD261ddSiWDpiqVEHGYiQMNijanmVBEZrs&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:1%7C#{@app.latitude},+#{@app.longitude}"
            br
            == "#{@app.latitude.to_s}, #{@app.longitude.to_s}"

app/views/applications/_audit.html.slim
ul
  - @app.versions.each do |v|
    - v.changeset.each do |f, d|
      -
      li== "#{f} changed from #{d[0] ? d[0] : 'new' } to #{d[1]}"

app/views/applications/_form.html.slim
== simple_form_for @app do |f|
  == f.input :title
  == f.input :first_name
  == f.input :last_name
  == f.input :address1, label: 'Address'
  == f.input :city
  == f.input :state
  == f.input :zip, as: :integer
  == f.submit

app/views/applications/_id_card.html.slim
.alert.alert-warning
  | <strong>YOUR APPLICATION IS APPROVED!</strong> Please print your ID card.
.row
  .col-md-6
    .card
      .card-block
        h3.card-title
          | Member ID Card
        .card-text
          table.table
            tr
              th Name
              td== "#{@app.last_name}, #{@app.first_name}"
            tr
              th Card #
              td== @app.card.card_number
            tr
              th Expires
              td== @app.card.expiration.strftime('%m/%d/%Y')
  .cold-md-6
    == link_to 'Print PDF ID Card', card_application_path(@app, format: :pdf), class: 'btn btn-primary'

app/views/applications/_notices.html.slim
.card
  .card-block
    h3.card-title Notices
    .card-text
      div.alert.alert-success
        | This is the most up-to-date information about your application.
      - if @app.card
        div.alert.alert-info
          | Card Issued: #{@app.card.card_number}
        div.alert.alert-warning
          | Please renew by #{(@app.card.expiration - 1.day).strftime('%m/%d/%Y')}
      - if flash.notice
        div.alert.alert-warning
          == flash.notice

app/views/applications/_supplements.html.slim
table.table.table-condensed.table-striped.table-bordered
  thead
    tr
      th Document
      th Status
      th Upload File
      - if current_user.admin
        th Actions
  tbody
    - @app.application_supplements.order(id: :asc).each do |s|
      tr
        td== s.title
        td== s.status
        td
          - if s.waiting?
            == form_for [@app, s] do |form|
              == form.file_field :document
              == form.submit "Upload"
          - else
              | Uploaded -
              == link_to "Preview", s.document.url
        - if current_user.admin
          td
            == link_to "Approve", approve_application_application_supplement_path(@app, s) unless s.approved? or s.denied?
            == link_to "Deny", deny_application_application_supplement_path(@app, s) unless s.denied? or s.approved?

app/views/applications/edit.html.slim
<h1>Applications#edit</h1>
<p>Find me in app/views/applications/edit.html.erb</p>

app/views/applications/index.html.slim
h1 All Applications
table.table-bordered.table-striped.table.table-condensed
  thead
    tr
      th Title
      th Status
      th Haiku
  tbody
    - @apps.each do |app|
      tr
        td== link_to app.show_title, app
        td== app.status
        td== app.haiku

app/views/applications/new.html.slim
h1 Apply for Membership
== render 'form'

app/views/applications/show.html.slim
h1 Application System
.row
  .col-md-8
    == render 'app_card'
  .col-md-4
    == render 'notices'
    - if @app.card
      == link_to 'Print PDF ID Card', card_application_path(@app, format: :pdf), class: 'btn btn-primary'
    == render 'audit'

== render 'supplements'
- if !@app.approved? && params['apv'] == 'true'
  == form_tag approve_application_path(@app), method: :patch do |f|
    == button_tag 'Approve'
// render 'id_card' if @app.approved?

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembershipApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        <%= current_user.email %> - <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm' %>
          - <%= link_to "New Application", new_application_path, class: 'btn btn-success btn-sm' %>
      <% end %>
      <hr>
      <%= yield %>
    </div>
  </body>
</html>